from pydantic import BaseModel, Field
from typing import Optional


class KeyTrend(BaseModel):
    trend: str
    impact: str  # "positive" | "negative" | "neutral"
    description: str


class IndustryOverview(BaseModel):
    sector: str
    summary: str
    market_size_usd_bn: Optional[float] = None
    cagr_pct: Optional[float] = None
    key_trends: list[KeyTrend]
    value_chain_stages: list[str]
    key_risks: list[str]
    regulatory_environment: str


class Competitor(BaseModel):
    name: str
    ticker: Optional[str] = None
    market_position: str  # "leader" | "challenger" | "niche"
    description: str
    key_strength: str
    key_weakness: str


class CompetitiveLandscape(BaseModel):
    market_structure: str  # e.g. "Oligopoly", "Fragmented", "Duopoly"
    dynamics_summary: str
    key_moat_types: list[str]
    competitors: list[Competitor]
    disruption_threats: list[str]


class PeerComp(BaseModel):
    ticker: str
    company_name: str
    market_cap_usd_bn: Optional[float] = None
    ev_ebitda: Optional[float] = None
    pe_ratio: Optional[float] = None
    revenue_growth_pct: Optional[float] = None
    gross_margin_pct: Optional[float] = None
    key_metric_label: Optional[str] = None
    key_metric_value: Optional[str] = None
    analyst_consensus: Optional[str] = None  # "Buy" | "Hold" | "Sell"


class InvestmentIdea(BaseModel):
    title: str
    type: str  # "long equity" | "short equity" | "thematic" | "private" | "credit"
    one_liner: str
    investment_thesis: str
    key_catalysts: list[str]
    key_risks: list[str]
    time_horizon: str  # e.g. "6-12 months", "2-3 years"
    conviction: str  # "high" | "medium" | "low"


class MarketResearchReport(BaseModel):
    query: str
    industry_overview: IndustryOverview
    competitive_landscape: CompetitiveLandscape
    peer_comps: list[PeerComp]
    ideas_shortlist: list[InvestmentIdea]
    disclaimer: str = (
        "This report is generated by an AI model and is for informational purposes only. "
        "It does not constitute investment advice. All figures are estimates and may not "
        "reflect current market conditions. Always conduct your own due diligence."
    )
